name: Techulus Push Notification

on: [push]

jobs:
  notify:
    steps:
      - uses: techulus/push-github-action@master
        env:
          API_KEY: 3ed759e8-7ce4-4400-bb04-5cb5f06674f4
          MESSAGE: Push hecho al repo de gh-actions-test