name: Techulus Push Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: techulus/push-github-action@master
        env:
          API_KEY: 3ed759e8-7ce4-4400-bb04-5cb5f06674f4
          MESSAGE: ${{github.actor}} has pushed to ${{github.repository}}